<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Debug Without Building</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicExpresso.Core" Version="2.19.2" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoulSmith.Asset\SoulSmith.Asset.csproj" />
    <ProjectReference Include="..\SoulSmith.Core\SoulSmith.Core.csproj" />
    <ProjectReference Include="..\SoulSmith.EmotionTag\SoulSmith.EmotionTags.csproj" />
    <ProjectReference Include="..\SoulSmith.Localization\SoulSmith.Localization.csproj" />
    <ProjectReference Include="..\SoulSmith.Object\SoulSmith.Object.csproj" />
    <ProjectReference Include="..\SoulSmith.Templates\SoulSmith.Templates.csproj" />
    <ProjectReference Include="..\SoulSmith.UnitStats\SoulSmith.UnitStats.csproj" />
	<ProjectReference Include="..\SoulSmith.Collections\SoulSmith.Collections.csproj" />
  </ItemGroup>

</Project>
