<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoulSmith.Battle\SoulSmith.Battle.csproj" />
    <ProjectReference Include="..\SoulSmith.Collections\SoulSmith.Collections.csproj" />
    <ProjectReference Include="..\SoulSmith.Core\SoulSmith.Core.csproj" />
    <ProjectReference Include="..\SoulSmith.Object\SoulSmith.Object.csproj" />
  </ItemGroup>

</Project>
