<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoulSmith.Asset\SoulSmith.Asset.csproj" />
    <ProjectReference Include="..\SoulSmith.Collections\SoulSmith.Collections.csproj" />
    <ProjectReference Include="..\SoulSmith.EmotionTag\SoulSmith.EmotionTag.csproj" />
    <ProjectReference Include="..\SoulSmith.UnitStats\SoulSmith.UnitStats.csproj" />
  </ItemGroup>

</Project>
